# Generated by Django 5.1 on 2024-08-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioAttachmet',
            new_name='AudioAttachment',
        ),
    ]
